name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  secrets-scan:
    name: GitLeaks - Detekcija tajni
    runs-on: ubuntu-latest
    steps:
      - name: Preuzmi kod
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pokreni GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml
  sast-semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      - name: Preuzmi kod
        uses: actions/checkout@v4

      - name: Pokreni Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
  sast-security-code-scan:
    name: SAST - Security Code Scan
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      - name: Preuzmi kod
        uses: actions/checkout@v4

      - name: Postavi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build sa Security Code Scan analizom
        run: |
          cd BankDemo
          dotnet build --no-incremental